### ISSUE TITLE
Computer Vision SDK for iOS

### ISSUE THREAD

**Issue by guodan** [Azure-Samples/cognitive-services-quickstart-code#103]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I want use OCR in iOS by computer vision sdk，but the document dosen't contains OC/Swift for iOS. 

### Expected/desired behavior
> I hope there is a computer vision sdk for iOS. 
> Thanks.

**Comment by v-jaswel** [comment]
Hello @guodan,
First I sincerely apologize for the delayed reply.
I have posted this request to User Voice:
https://cognitive.uservoice.com/forums/430309-computer-vision/suggestions/41763817-please-create-computer-vision-sdk-for-ios
and forwarded the request to the Computer Vision team.
Thank you,
v-jaswel
