### ISSUE TITLE
operations\_apps_operations.py - Error

### ISSUE THREAD

**Issue by shakanand** [Azure-Samples/cognitive-services-quickstart-code#135]
When i am trying to run the python code, it fails with the below error.  I have the correct key and endpoint URL in it.

https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/python/LUIS/python-sdk-authoring-prediction/application_quickstart.py

Creating application...
Traceback (most recent call last):
  File "c:/zz Temp 01/py luis/pyluis.py", line 181, in <module>
    app_id, app_version = create_app()
  File "c:/zz Temp 01/py luis/pyluis.py", line 49, in create_app
    culture=app_locale))
  File "C:\Users\zzzz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\cognitiveservices\language\luis\authoring\operations\_apps_operations.py", line 85, in add
    raise models.ErrorResponseException(self._deserialize, response)
azure.cognitiveservices.language.luis.authoring.models._models_py3.ErrorResponseException: Operation returned an invalid status code 'Access Denied'

**Comment by v-jaswel** [comment]
Hello @shakanand,

First, I respectfully apologize for this very delayed reply.

I have been trying to find out why that code might give you an "access denied" error with a valid endpoint and subscription key, but so far I am unable to reproduce the issue.

If possible, can you try to use your endpoint and authoring key in the API test console? That would help us narrow down whether this is an issue with the SDK or with the endpoint and subscription key.

The following URL is the API test console for the "get applications list" command, which can be called at any time. If you set the `Host > Name` drop-down menu to "[resource name].cognitiveservices.azure.com", you can then enter your LUIS resource name in the `Resource Name` textbox. For example if your endpoint was `https://my_endpoint.cognitiveservices.azure.com` you would just enter `my_endpoint` as the `Resource Name`.
https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c30/console

Thank you for your patience and again my apologies for the delay.
v-jaswel

**Comment by v-jaswel** [comment]
Hello @shakanand,

I am going to close this issue for now due to lack of activity, but please feel free to reopen it.

Thank you,
v-jaswel
