### ISSUE TITLE
'ComputerVisionClient' object has no attribute 'batch_read_file_in_stream'

### ISSUE THREAD

**Issue by mehtajainam** [Azure-Samples/cognitive-services-quickstart-code#166]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> recognize_handwriting_results = computervision_client.batch_read_file_in_stream(local_image_handwritten, raw=True)

### Any log messages given by the failure
>AttributeError: 'ComputerVisionClient' object has no attribute 'batch_read_file_in_stream'

### Expected/desired behavior
>

### OS and Version?
> Operating System: Ubuntu 18.04.4 LTS
   Kernel: Linux 5.3.0-1028-azure

### Versions
> azure-cognitiveservices-vision-computervision 0.7.0

### Mention any other details that might be useful
I'm trying to perform handwriting recognition on a local image that I have. Using the example provided in ComputerVisionQuickstart.py, I was able to get the remote example to work, but when trying with the local image, I keep getting the error 'ComputerVisionClient' object has no attribute 'batch_read_file_in_stream'. Is there something I might be doing wrong, or does the ComputerVisionClient no longer support local images?

**Comment by ToddVan** [comment]
I can confirm this is an issue. 

In my case its on a Raspberry Pi 3

**Comment by PatrickFarley** [comment]
This has since been corrected

**Comment by PatrickFarley** [comment]
#please-close

**Comment by PatrickFarley** [comment]
#please-close

**Comment by muditchaudhary** [comment]
I still encounter this issue on MacOS Big Sur Version 11.2 Beta

**Versions**
> azure.cognitiveservices.vision.computervision version 0.7.0

**Minimal steps to reproduce**  
>`recognize_handwriting_results = computervision_client.batch_read_file_in_stream(local_image_handwritten, raw=True)`
