### ISSUE TITLE
Errors in the image classification Program.cs

### ISSUE THREAD

**Issue by ChrisPetit** [Azure-Samples/cognitive-services-quickstart-code#185]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
cognitive-services-quickstart-code/dotnet/CustomVision/ImageClassification/Program.cs
Line 28: TrainingApi is with a capital T and the rest of the references are with an undercast t...

### Any log messages given by the failure
>

### Expected/desired behavior
This shows up before compilation in visual studio. -

### OS and Version?
Visual Studio 2019 on windows 10

### Versions
>

### Mention any other details that might be useful
there might be more issues in the code...for instance the fact that the main method is static and the other methods are not. Just try to compile it and please fix the errors....

**Comment by v-jaswel** [comment]
Hello @ChrisPetit,

I apologize for my delayed reply. You are correct that that sample had a number of issues. I have fixed them and am now able to compile and run it as expected. Please let me know if you encounter any further issues with the sample.
Thank you for the feedback and your patience.
v-jaswel
