### ISSUE TITLE
Emotions and Facial Hair Broken in the DetectFaceAttributes.py file

### ISSUE THREAD

**Issue by Codingboy65** [Azure-Samples/cognitive-services-quickstart-code#195]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
https://stackoverflow.com/questions/65246616/python-formatting-dictionaries-within-dictionary?noredirect=1#comment115349649_65246616
>

### Any log messages given by the failure
>

### Expected/desired behavior
Facial attributes detected:
Gender: male
Emotion: 0% anger, 0% contempt, 0% disgust, 0% fear, 0% happiness, 98% neutral, 0% sadness, 0% surprise
>

### OS and Version?
> Windows 10 pro

### Versions
>

### Mention any other details that might be useful

when face.face_attributes.emotion is printed I get:
{'additional_properties': {}, 'anger': 0.001, 'contempt': 0.002, 'disgust': 0.0, 'fear': 0.0, 'happiness': 0.542, 'neutral': 0.455, 'sadness': 0.0, 'surprise': 0.0}

Would be more convenient to have it like so:
Emotion: 0% anger, 0% contempt, 0% disgust, 0% fear, 0% happiness, 98% neutral, 0% sadness, 0% surprise

For more details please look at the StackOverflow link I put above

**Comment by v-jaswel** [comment]
Hi @Codingboy65,

Thank you for your feedback and I apologize for my delayed reply. I have updated this code sample per your feedback. It now prints the emotion attributes individually rather than simply dumping the emotion object.
v-jaswel

**Comment by Codingboy65** [comment]
Thanks, I worked out a solution before this update. 
`emotionObject = face.face_attributes.emotion.as_dict()`
`emotion_fin = (', '.join([f'{v:.0%} {k}' for k, v in emotionObject.items() if k != 'additional_properties']))`
