### ISSUE TITLE
Unable to get the response 

### ISSUE THREAD

**Issue by ShamineDsouza** [Azure-Samples/cognitive-services-quickstart-code#199]
Unable to get a response .
Does not pull out of this code line to give a response.
 response = await client.PostAsync(uri, content);

PLease help.

**Comment by v-jaswel** [comment]
Hello @ShamineDsouza ,

I apologize for my delayed reply.
It looks like you are referring to the .NET Face sample:
https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/67a5c085a0cebdf0f70ec3e151b5fd57f7408347/dotnet/Face/rest/detect.cs#L78

I am currently able to run this sample as follows:

1. Download the following face image: https://wallup.net/wp-content/uploads/2016/06/06/97657-glasses-brunette-smiling-face-closeup-amateur-748x1122.jpg
2. Save the image to the `bin\Debug\netcoreapp3.1\` folder of the .NET Core solution that I am using to run the Face sample. This puts the image in the same folder as the .exe.
3. Run the sample. When the prompt `Enter the path to an image with faces that you wish to analyze:` appears, enter:
```
97657-glasses-brunette-smiling-face-closeup-amateur-748x1122.jpg
```

That gives me the response:
```
Wait a moment for the results to appear.

Response:

[
   {
      "faceId": "9c62d27f-651c-4238-8893-ed932b98c361",
      "faceRectangle": {
         "top": 190,
         "left": 52,
         "width": 536,
         "height": 683
      }
   }
]
```

If you are not receiving a response using this method, can you tell me what image you are submitting and where I can obtain the image? I can then try to reproduce the issue.

Thank you,
v-jaswel

**Comment by v-jaswel** [comment]
Hello,

I am going to close this issue for now due to lack of activity, but please feel free to reopen it.

Thank you,
v-jaswel
