### ISSUE TITLE
(Invalid URI: The URI scheme is not valid)

### ISSUE THREAD

**Issue by Abdulrahman-Shabaka** [Azure-Samples/cognitive-services-quickstart-code#206]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
(Invalid URI: The URI scheme is not valid)
I just wanna know what is this URL referees ti cause it keeping sending me invalid URL and  I didn't get any comment for what this URL refers to or should lead to 
the URL is the next one
(https://csdx.blob.core.windows.net/resources/Face/Images/
![prob 1](https://user-images.githubusercontent.com/73299367/104908599-65ea9580-598f-11eb-9d10-bdc8d3ee5a35.png)
)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ChrisHMSFT** [comment]
Hi @Abdulrahman-Shabaka ,

Can you please share which file and cognitive service you looking at when you hit this issue?

Thanks!
Chris

**Comment by Abdulrahman-Shabaka** [comment]
hi @ChrisHMSFT,

thank you for your response.
well I was doing the steps as shown in the quickstart for face API on the Microsoft website
 (https://docs.microsoft.com/en-us/azure/cognitive-services/Face/Quickstarts/client-libraries?pivots=programming-language-csharp&tabs=visual-studio#authenticate-the-client)
 when I try to run the code to test the detection this error comes up as shown in the picture and there is no description for what this URL leads to or what is its job on the website.
I will be grateful to you if you told me what is IMAGE_BASE_URL or lead me to any documentation that explains it.
![baseurl](https://user-images.githubusercontent.com/73299367/105046752-26e14080-5a72-11eb-9293-96fad5b4a5d3.png)
 
![prob 1](https://user-images.githubusercontent.com/73299367/105046535-e386d200-5a71-11eb-95b9-c058c7415742.png)

**Comment by v-jaswel** [comment]
Hello @Abdulrahman-Shabaka,

That link (https://csdx.blob.core.windows.net/resources/Face/Images/) is not working for me either. It is supposed to point to a folder of sample images that are used by the quickstart. I will try to find out what is wrong with it.

Thank you,
v-jaswel

**Comment by v-jaswel** [comment]
Hello @Abdulrahman-Shabaka,

Looking at your screenshot, I see you have angle brackets (&lt; and &gt;) at the beginning and end of the values of SUBSCRIPTION_KEY, ENDPOINT, and IMAGE_BASE_URL. The angle brackets are probably causing the error and should be removed.

The URL https://csdx.blob.core.windows.net/resources/Face/Images/ is not intended to work on its own. The application adds filenames to the end of that URL, for example https://csdx.blob.core.windows.net/resources/Face/Images/Family1-Dad1.jpg, and the resulting URLs will then work.

Please let me know if this resolves the issue.
Thank you,
v-jaswel

**Comment by Abdulrahman-Shabaka** [comment]
@v-jaswel  
thanks a lot this was the problem and I solved it and you also give me a point for how to browse this URL I really grateful to you

**Comment by v-jaswel** [comment]
Hello @Abdulrahman-Shabaka,

My pleasure, I am glad to hear that resolved your issue. I will go ahead and close this issue.
Thank you,
v-jaswel
