### ISSUE TITLE
Cognitive servIce -Form Recogniser sample code in Azure Documentation

### ISSUE THREAD

**Issue by dynamodhiraj** [Azure-Samples/cognitive-services-quickstart-code#211]
> Please provide us with the following information:
> ---------------------------------------------------------------

The code samples provided for Form recogniser lacks pre requisite information .
The 'Setting up’ instruction is inadequate as there is no information on Python setup for Azure.
The python interpreter fails to recognise Azure libraries in visual studio code.
There needs additional instruction on the setup to enable users to guide through the process.
Needs detailed documentation on the setup for partners ..

I get the following error:-

Traceback (most recent call last):
  File "/Users/visiothoughts/Documents/Visiothoughts/Work-Project/AI-Moto/com/ai/Bill-Recogniser/RecogniseFormContent.py", line 5, in <module>
    from azure.core.exceptions import ResourceNotFoundError
ModuleNotFoundError: No module named ‘azure'

https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/quickstarts/client-library?tabs=ga%2Cv2-0&pivots=programming-language-python

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Install the Form recogniser code in Visual Studio code 
Yes .

Run pip3 install azure-ai-formrecognizer
----pip 21.0 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)
python—version
----Python 3.9.1

### Any log messages given by the failure
>
Traceback (most recent call last):
  File "/Users/visiothoughts/Documents/Visiothoughts/Work-Project/AI-Moto/com/ai/Bill-Recogniser/RecogniseFormContent.py", line 5, in <module>
    from azure.core.exceptions import ResourceNotFoundError
ModuleNotFoundError: No module named 'azure'

### Expected/desired behavior
> Expected the Form recogniser code to run as per the code snippets in the document
https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/quickstarts/client-library?tabs=ga%2Cv2-0&pivots=programming-language-python
<img width="1440" alt="Screen Shot 2021-01-27 at 23 00 46" src="https://user-images.githubusercontent.com/31129199/106065737-9e0e7880-60f3-11eb-9193-3d2414adfbfe.png">
<img width="1440" alt="Screen Shot 2021-01-27 at 23 00 46" src="https://user-images.githubusercontent.com/31129199/106065779-ae265800-60f3-11eb-95ac-4cadb1dfcf20.png">

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Mac OS Sienna

### Versions
>Sienna

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by v-jaswel** [comment]
Hello @dynamodhiraj,

Thank you for bringing this to our attention and for providing a very thorough error report, that is much appreciated when trying to resolve an issue such as this.
I apologize for the missing instruction.
To set up Azure for Python, you will want to run:

```cmd
python -m pip install azure.core
```

I will add that to the Form Recognizer Python quickstart document. As well, I will review the quickstart to see if there are any other instructions that need to be added to make sure it can be run.
Meanwhile, please let me know if you encounter any other issues with this quickstart.

Thank you,
v-jaswel

**Comment by v-jaswel** [comment]
Hello,

I am going to close this issue for now due to lack of activity, but please feel free to reopen it.

Thank you,
v-jaswel
