### ISSUE TITLE
 Incorrect duplication of code lines in the python file CustomVisionQuickstart.py

### ISSUE THREAD

**Issue by agribot2** [Azure-Samples/cognitive-services-quickstart-code#213]
Are the code lines 80 - 84 in the python file CustomVisionQuickstart.py  incorrect duplicates of the code line directly before them ?

-->
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Visual study of the lines of code 74 - 84 in the python code file CustomVisionQuickstart.py

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by v-jaswel** [comment]
Hi @agribot2,

Thank you for reporting this. I could find no reason for the duplicate code and have removed it from the first snippet (snippet_train).
v-jaswel
