### ISSUE TITLE
Custom Model Input Requirements are Incorrect

### ISSUE THREAD

**Issue by anujb-msft** [Azure-Samples/cognitive-services-quickstart-code#219]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Navigate to https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/python/FormRecognizer/rest/python-train-extract.md#L50
>Review https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/python/FormRecognizer/rest/python-train-extract.md#train-a-form-recognizer-model

### Any log messages given by the failure
>NA

### Expected/desired behavior
>Should delineate custom training data input requirements here:
https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/build-training-data-set

### OS and Version?
> NA

### Versions
> NA

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by fsharpn00b** [comment]
Hello @anujb-msft,

First, I humbly apologize for my very delayed reply to this issue.

https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/python/FormRecognizer/rest/python-train-extract.md does include a link to https://docs.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/build-training-data-set where the custom model input requirements are delineated. After talking to the product team, I have placed this link in a note to make it more visible.

I will close this issue for now, but please feel free to reopen it if I have misunderstood the issue or if you believe it has not been fully addressed.

Thank you!
fsharpn00b
