### ISSUE TITLE
How to use Form Recognizer code in ASP.NET or in ASP.Net MVC or ASP.Net Core or ASP.NET Core MVC?

### ISSUE THREAD

**Issue by ChetanChaudhari03** [Azure-Samples/cognitive-services-quickstart-code#23]
Hi Team,

> ### **Form Recognizer**

I use provided console application code in .Net its work that's grate.
**But when i use same code in ASP.NET its not working?** So could you or anyone can help me for that.

Thanks,
Chetan Chaudhari

**Comment by ramparab** [comment]
Hello Chetan, can you please elaborate on specific issue you are running into? Please share error code \ exception details that will help me take a look. 

Thanks much!
-Sandeep

**Comment by ChrisHMSFT** [comment]
@ChetanChaudhari03  closing the issue since there hasn't been a response. Please re-open if you are still experiencing the issue.

Thanks!
Chris
