### ISSUE TITLE
AttributeError: 'ComputerVisionClient' object has no attribute 'batch_read_file_in_stream'

### ISSUE THREAD

**Issue by 1144181135** [Azure-Samples/cognitive-services-quickstart-code#233]
Hi teams of Azure. I try to read ocr result from a local image. I can normally read a ocr result from the remote url. Then, I follow the code in "https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/python/ComputerVision/ComputerVisionQuickstart.py"  -- "Batch Read File - local". But "AttributeError:ComputerVisionClient' object has no attribute 'batch_read_file_in_stream'" happens.

**Comment by BART1968** [comment]
Hi exact the same thing here.  I'm Using python 3.9.2
I read somewere using:   recognize_handwriting_results = computervision_client.batch_read_in_stream(local_image_handwritten, raw=True)  
Same error.

**Comment by fsharpn00b** [comment]
Hi @1144181135  and @BART1968 , I am investigating this now.

It looks like the "batch_read_file_in_stream" method was removed from the latest release of Custom Vision in the Azure SDK for Python:
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py

I am trying to fix the sample and determine the correct replacement method. My guess is that it might be recognize_printed_text_in_stream. I will let you know as soon as I have the sample working again. Thank you for bringing this to our attention and for your patience.

**Comment by 1144181135** [comment]
> Hi exact the same thing here. I'm Using python 3.9.2
> I read somewere using: recognize_handwriting_results = computervision_client.batch_read_in_stream(local_image_handwritten, raw=True)
> Same error.

hi, I use recognize_handwriting_results = computervision_client.read_in_stream(local_image_handwritten, raw=True) which is normal to extract local image handwrite results.

**Comment by 1144181135** [comment]
> Hi @1144181135 and @BART1968 , I am investigating this now.
> 
> It looks like the "batch_read_file_in_stream" method was removed from the latest release of Custom Vision in the Azure SDK for Python:
> https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py
> 
> I am trying to fix the sample and determine the correct replacement method. My guess is that it might be recognize_printed_text_in_stream. I will let you know as soon as I have the sample working again. Thank you for bringing this to our attention and for your patience.

Thank you. I use "read_in_stream" and run it successfully.

**Comment by fsharpn00b** [comment]
Hi @1144181135 ,
cc @BART1968 

Thank you! I have updated the sample to use read_in_stream and get_read_result, and tested it successfully. Please note I also changed it to look for the images in an "images" folder in the same location as the sample, rather than in "/resources" (at the root of the file system).

**Comment by BART1968** [comment]
> Hi @1144181135 ,
> cc @BART1968
> 
> Thank you! I have updated the sample to use read_in_stream and get_read_result, and tested it successfully. Please note I also changed it to look for the images in an "images" folder in the same location as the sample, rather than in "/resources" (at the root of the file system).

Thank you for the support, and follow up, I have a look at it, cheers, Bart
