### ISSUE TITLE
is TRUE "read_status" to "read.result"

### ISSUE THREAD

**Issue by junando** [Azure-Samples/cognitive-services-quickstart-code#246]
https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/99f12f6e13d80b849944a3e9bce974413eb8832f/python/ComputerVision/ComputerVisionQuickstart.py#L740

**Comment by fsharpn00b** [comment]
Hello @junando ,

I apologize for my delayed reply. This issue should now be fixed by https://github.com/Azure-Samples/cognitive-services-quickstart-code/pull/248 which I have just merged.
