### ISSUE TITLE
Update SDK for Text Analytics service in the multi-language sample

### ISSUE THREAD

**Issue by ChrisHMSFT** [Azure-Samples/cognitive-services-quickstart-code#253]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/python/Multi-Service/text_analytics_cs.py

This still points to the older library for TA

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by fsharpn00b** [comment]
Done, although we might want to consider retiring this sample. Its purpose (per a comment that I removed) was apparently to demonstrate the "general Cognitive Services subscription key and endpoint". As far as I know, we no longer offer such a thing. Meanwhile this sample does not cover anything that is not already included in https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/python/TextAnalytics/python-v3-client-library.py.

**Comment by fsharpn00b** [comment]
Closing this issue as the work is done.
