### ISSUE TITLE
predictionApi should call AuthenticatePrediction() method

### ISSUE THREAD

**Issue by gottagetgit** [Azure-Samples/cognitive-services-quickstart-code#257]
https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/828729ec8b796eff27e07d386dfbe4f0d23c1daf/dotnet/CustomVision/ObjectDetection/Program.cs#L29

There is a method called AuthenticatePrediction() which is uncalled, while AuthenticateTraining() is called twice. The result is the same because the code is the same.

So perhaps there should only be one Authenticate() method.

**Comment by gottagetgit** [comment]
Pull request generated here #259

**Comment by fsharpn00b** [comment]
Hi @gottagetit,

Thank you very much for the PR, which I have just merged. Accordingly, I will now close this issue.
