### ISSUE TITLE
Code unable to compile; remove nullable type to fix

### ISSUE THREAD

**Issue by gottagetgit** [Azure-Samples/cognitive-services-quickstart-code#258]
https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/828729ec8b796eff27e07d386dfbe4f0d23c1daf/dotnet/Face/FaceQuickstart.cs#L157

Line should be using the non-nullable type:
>> returnFaceAttributes: new List<FaceAttributeType>{ ...

Otherwise causes an error in Visual Studio and unable to compile.

**Comment by fsharpn00b** [comment]
Thank you @gottagetgit . You're right, they changed the type of that parameter in March. I have updated the sample.
