### ISSUE TITLE
Face quickstart fails to compile

### ISSUE THREAD

**Issue by RohitMungi-MSFT** [Azure-Samples/cognitive-services-quickstart-code#262]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Run the face quickstart sample and it fails to compile with following error:

Code:
https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/dotnet/Face/FaceQuickstart.cs

Error:
Severity Code Description Project Line File Suppression State
Error CS1503 Argument 2: cannot convert from 'System.Collections.Generic.List<System.Guid?>' to 'System.Collections.Generic.IList<System.Guid>' analyze-faces 411 C:\Users\gsutt\source\repos\AI-102-AIEngineer\19-face\C-Sharp\face-api\Program.cs N/A

### Any log messages given by the failure
>
Severity Code Description Project Line File Suppression State
Error CS1503 Argument 2: cannot convert from 'System.Collections.Generic.List<System.Guid?>' to 'System.Collections.Generic.IList<System.Guid>' analyze-faces 411 C:\Users\gsutt\source\repos\AI-102-AIEngineer\19-face\C-Sharp\face-api\Program.cs N/A

### Expected/desired behavior
>
Code should compile and the quickstart should work for all scenarios

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10, VS 2019, .net core 3.1
### Versions
>
Windows 10, VS 2019, .net core 3.1

### Mention any other details that might be useful
Replace the following lines with the below lines:

429:
            List<Guid> sourceFaceIds = new List<Guid>();

571:
            List<Guid> faceIds = new List<Guid>();

Issue raised on docs repo. 
https://github.com/MicrosoftDocs/azure-docs/issues/77515
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by fsharpn00b** [comment]
Hello @RohitMungi-MSFT,

Thank you for filing this issue and I apologize for my delayed reply. I have updated the quickstart to resolve it.
Best regards
