### ISSUE TITLE
"'this.Endpoint' cannot be null." -> DOTNET C#

### ISSUE THREAD

**Issue by Atili0** [Azure-Samples/cognitive-services-quickstart-code#49]
I download the example and i tried to build the app, but when I run the app, I am getting this error

  | Name | Value | Type
-- | -- | -- | --
  | Message | "'this.Endpoint' cannot be null." | string

![image](https://user-images.githubusercontent.com/5795436/68373459-44fba300-0143-11ea-95e8-b17dbaad0bf6.png)

what can i do? i review all my keys but I dont find solution,

**Comment by DrXoo** [comment]
I have the same issue at doing the example. 

I am guessing that the endpoint to the blob storage is not correct as It seems to get files from the base path of the blob storage.

**Comment by DrXoo** [comment]
Nevermind.

The problem was the property _formRecognizerEndpoint_. I don't have that environment variable set neither in my machine or for my user.

**Comment by ChrisHMSFT** [comment]
Hi @Atili0 

Your issue appears the same as @DrXoo 's were you able to get the sample running?

Thanks,
Chris

**Comment by ChrisHMSFT** [comment]
Closing this ticket since there hasn't been any response. thanks!
