### ISSUE TITLE
How Can I use local image to request "face detect" function?

### ISSUE THREAD

**Issue by BITWN** [Azure-Samples/cognitive-services-quickstart-code#97]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I follow the doc “ https://docs.microsoft.com/zh-cn/azure/cognitive-services/face/quickstarts/client-libraries?pivots=programming-language-python&tabs=windows#detect-faces-in-an-image”， but change the "single_face_image_url" to local image file path.

### Any log messages given by the failure
> APIErrorException: (InvalidURL) Invalid image URL.
>I didn't found any information about how to request by local image.

### Expected/desired behavior
>Descriptions about how to request by local file.

### OS and Version?
> Windows 10.

### Versions
> 

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wiazur** [comment]
Hi @BITWN, there is a detect Face for local images here:
https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/python/Face/DetectIdentifyFace.py

The code is slightly different from detecting with a URL:
```
        # BufferedReader
        image = open(image_name, 'rb') 

        # Returns list[DetectedFace]
        faces = client.face.detect_with_stream(image)   
```

Here is the API reference, you can see what to do with a list of Detected Face:
https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-face/azure.cognitiveservices.vision.face.operations.faceoperations?view=azure-python#detect-with-stream-image--return-face-id-true--return-face-landmarks-false--return-face-attributes-none--recognition-model--recognition-01---return-recognition-model-false--detection-model--detection-01---custom-headers-none--raw-false--callback-none----operation-config-

**Comment by shub-garg** [comment]
> Hi @BITWN, there is a detect Face for local images here: https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/python/Face/DetectIdentifyFace.py
> 
> The code is slightly different from detecting with a URL:
> 
> ```
>         # BufferedReader
>         image = open(image_name, 'rb') 
> 
>         # Returns list[DetectedFace]
>         faces = client.face.detect_with_stream(image)   
> ```
> 
> Here is the API reference, you can see what to do with a list of Detected Face: https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-face/azure.cognitiveservices.vision.face.operations.faceoperations?view=azure-python#detect-with-stream-image--return-face-id-true--return-face-landmarks-false--return-face-attributes-none--recognition-model--recognition-01---return-recognition-model-false--detection-model--detection-01---custom-headers-none--raw-false--callback-none----operation-config-

How can we use an already opened cv2 image with azure face API, without having to save it again?
